# These are supported funding model platforms

github: [Lovely-02]
patreon:
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee:
thanks_dev:
custom: ["https://afdian.com/a/lovely02"]
